# Generated by Django 4.2.7 on 2024-05-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Querie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
