# Generated by Django 4.2.7 on 2024-05-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyster', '0002_querie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queries',
        ),
    ]
