# Generated by Django 4.2.7 on 2024-05-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyster', '0003_delete_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querie',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
